apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops.name" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aiops.name" . }}
  ports:
    - name: http
      port: 8000
      targetPort: http
